version: 2
updates:
  # Python dependencies
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rxchi1d"
    assignees:
      - "rxchi1d"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    # 優先處理安全性更新和直接依賴
    allow:
      - dependency-type: "direct"
    # 忽略非關鍵的 patch 版本更新（減少 PR 數量）
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      # 核心依賴：主要功能套件
      core-dependencies:
        patterns:
          - "py7zz"
          - "zstandard"
          - "blake3"
          - "par2cmdline-turbo"
      # CLI 依賴：使用者介面相關
      cli-dependencies:
        patterns:
          - "typer"
          - "rich"
          - "pydantic"
          - "loguru"
      # 開發依賴：測試與程式碼品質
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff*"
          - "mypy*"
          - "build"
          - "twine"
          - "*-cov"
          - "*-asyncio"
      # 建置依賴：專案建置工具
      build-dependencies:
        patterns:
          - "hatchling"
          - "hatch-*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rxchi1d"
    assignees:
      - "rxchi1d"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
