repos:
  # Standard file checks (trailing whitespace, file endings, etc.)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict

  # Fast linting and formatting (pre-commit only)
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check . --output-format=github
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

      - id: ruff-format-check
        name: ruff format check
        entry: uv run ruff format --check --diff .
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

      - id: mypy-check
        name: mypy type check
        entry: uv run mypy src/
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

  # Test suite (pre-push only)
  - repo: local
    hooks:
      - id: pytest
        name: pytest test suite
        entry: uv run pytest -v --tb=short
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]
