repos:
  # Standard file checks (fast and essential)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files

  # Script-based comprehensive checks
  - repo: local
    hooks:
      - id: quick-ci-check
        name: Quick CI checks (ruff + mypy)
        entry: ./scripts/quick-check.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]
        verbose: true

      - id: basic-functionality-test
        name: Basic functionality tests
        entry: uv run pytest tests/test_config.py tests/test_utils.py -v --tb=line
        language: system
        pass_filenames: false
        stages: [pre-push]
        verbose: true