name: Bug Report
description: Create a report to help us improve coldpack
title: "fix: [brief description of the bug]"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Use archive file '...'
        3. Execute function '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Ubuntu (specify version in additional context)
        - macOS (specify version in additional context)
        - Windows (specify version in additional context)
        - Other Linux distribution
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What Python version are you using?
      options:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: coldpack-version
    attributes:
      label: coldpack Version
      description: What version of coldpack are you using? (run `cpack --version` or `python -c "import coldpack; print(coldpack.__version__)")`)
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install coldpack?
      options:
        - pip install coldpack
        - pip install from GitHub
        - Source installation (git clone)
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: If applicable, paste any error messages here
      render: shell
      placeholder: Paste error messages here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including specific OS versions, archive types, file sizes, etc.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested with the latest version of coldpack
          required: true
        - label: I have provided all the required information above
          required: true