name: Auto Label PRs

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Label PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true

  conventional-label:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const prNumber = context.payload.pull_request.number;

            // Define label mappings for conventional commit types
            const labelMap = {
              'feat': 'feat',
              'fix': 'fix',
              'docs': 'docs',
              'style': 'style',
              'refactor': 'refactor',
              'perf': 'perf',
              'test': 'test',
              'chore': 'chore',
              'ci': 'ci',
              'build': 'ci',
              'revert': 'revert'
            };

            // Extract conventional commit type from title
            const conventionalPattern = /^(\w+)(\(.+\))?: .+/;
            const match = title.match(conventionalPattern);

            if (match) {
              const commitType = match[1];
              const label = labelMap[commitType];

              if (label) {
                try {
                  await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: prNumber,
                    labels: [label]
                  });
                  console.log(`Added label "${label}" to PR #${prNumber}`);
                } catch (error) {
                  console.log(`Failed to add label: ${error.message}`);
                }
              }
            } else {
              console.log(`Title "${title}" doesn't match conventional commit pattern`);
            }
